apiVersion: skaffold/v3
kind: Config
metadata:
  name: fibonacci
build:
  artifacts:
    - image: registry.orb.local/server
      ko: {}
  local:
    push: false
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/observability.yaml
    - k8s/server.yaml
