apiVersion: v1
kind: Service
metadata:
  name: hyperdx
  namespace: fibonacci
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: collector
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry
  namespace: fibonacci
spec:
  ports:
    - port: 4317
      name: otlp-grpc
    - port: 4318
      name: otlp-http
  type: ClusterIP
  selector:
    app: collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: fibonacci
spec:
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: docker.hyperdx.io/hyperdx/hyperdx-local:2
          ports:
            - containerPort: 4137
            - containerPort: 4138
            - containerPort: 8080
